agittins/bermuda

custom_components/bermuda/config_flow.py
custom_components/bermuda/manifest.json

- revert change from "helper" back to "device" integration_type.
- remove deprecated CONNECTION_CLASS config var.

(fix) Revert from helper to device

---

custom_components/bermuda/__init__.py
custom_components/bermuda/const.py

- fixed using stale adverts for area prescense decisions
- fixed handling of scanners that are not allocated to an area

(fix) Ignore stale adverts for area presence

---

.github/release-drafter.yml
.github/workflows/release.yaml
custom_components/bermuda/const.py
custom_components/bermuda/entity.py
custom_components/bermuda/manifest.json

- note in const that version is set by release only
- tweaks to release.yaml
- remove version info from entity.py since devices/entities don't need it.
- set repo version of manifest.json back to 0.0.0
- lifted some release settings from spook

chore: Versioning and release clean-ups

---

custom_components/bermuda/entity.py

- clear model info for existing devices (previously set to version / 0.0.0, which is confusing and not helpful).

fix: Clear version info from entity model number

---

custom_components/bermuda/__init__.py

- Logging when a device changes its advertised TX-Power is now debug-logged instead of warning (was initially warning to find out if people actually have devices that do this. They do).

perf: Downgrade TX Power change log to debug

---

custom_components/bermuda/__init__.py
custom_components/bermuda/config_flow.py
custom_components/bermuda/const.py
custom_components/bermuda/device_tracker.py
custom_components/bermuda/sensor.py
custom_components/bermuda/translations/en.json

- Added a distance sensor for each proxy on each tracked device.
- fixed defaults for radius and timeout not applying correctly
- fixed initialisation of sensors at system start, they are now created via callback from the data processor.
- Implemented method for sensor platform to positively indicate the sensors were created (`sensor_created`)
- Perform full re-scan of restored scanners to catch any changes since last save.
- initialise zone as STATE_UNAVAILABLE
- fix unique-id mappings and pin them to mac address more directly instead of inheriting from the parent classes.
- implement `unit_of_measurements` to get distances appearing as graphable more cleanly than the native property did.

(feat) Per-proxy distance sensors

---

.github/workflows/tests.yaml
.gitignore
.isort.cfg
.pre-commit-config.yaml
custom_components/__init__.py
custom_components/bermuda/__init__.py
custom_components/bermuda/binary_sensor.py
custom_components/bermuda/config_flow.py
custom_components/bermuda/const.py
custom_components/bermuda/device_tracker.py
custom_components/bermuda/entity.py
custom_components/bermuda/sensor.py
custom_components/bermuda/switch.py
requirements_test.txt
tests/__init__.py
tests/conftest.py
tests/const.py
tests/test_config_flow.py
tests/test_init.py
tests/test_switch.py

Includes WIP on supporting passive bluetooth data updates (because lazy).
- replaces reorder-imports with isort, see https://github.com/psf/black/issues/4175
- (ri is stubbornly extending beyond its stated singular goal and douchebaggery is prohibiting fixing it)
- big thanks to @jaymunro for tracking down the core issue at https://github.com/agittins/bermuda/pull/114

Chore: Replace reorder-imports with isort

---

custom_components/bermuda/__init__.py

- added `mac_is_random` field to device structure to flag generated mac addresses, hopefully.
- shortened update_interval from 5 seconds to 0.9 seconds. *this might impact performance, maybe*
- removed some dead code, cleanups and linting
- removed passiveBluetoothDataUpdateCoordinator attempt (*might* address a startup issue with 2024.3.0)

Add mac_is_random, shorten update_interval, cleanups

---

custom_components/bermuda/__init__.py
custom_components/bermuda/const.py
custom_components/bermuda/translations/en.json

- Distances older than DISTANCE_TIMEOUT are regarded as too old, and device is marked as out of range by setting rssi_distance to None.
- Filter history is cleared for devices that have gone out of range
- Initial steps to apply rate-limiting for sensor values.
- Made backend update_interval back to constant (rather than config) and 1.05 seconds.

fix: Add timeout logic for distance measurements

---

custom_components/bermuda/__init__.py

- feat: ignore distance readings that would require unlikely velocity
- if reading would require a retreating velocity above MAX_VELOCITY, ignore it when smoothing distances.
- fix: clarification around how out of range devices are decided.

feat: Ignore long distance readings that would require high velocity

---

custom_components/bermuda/__init__.py
custom_components/bermuda/entity.py
custom_components/bermuda/sensor.py

- fix: Fix updates for local USB scan entries
- There was a bug where the device.scanner data wasn't being updated if the scanner was no longer providing (caching) an advertisement for that device. This mainly showed up on local usb bluetooth dongles, because I think BlueZ would expunge the advert history more quickly than we timeout a distance reading (30 sec by default). The result would be that out-of-range devices would snap to the last distance recorded by the usb adaptor, since we never cleaned it up previously. This might also result in other fixes but I haven't seen cases where proxies would drop advert caches.
- Removed have_new_stamp and refactored it to be indicated by new_stamp being None. Preserved into self.new_stamp and split the calculate_data() step out of t
he …

fix: Fix updates for local USB scan entries

---

README.md
custom_components/bermuda/__init__.py
custom_components/bermuda/const.py
custom_components/bermuda/entity.py
custom_components/bermuda/sensor.py

- 🚀 feat: iOS / iPhone Support with IRK #135 
- Integrated with the `Private BLE Device` integration. Any devices set up in Private BLE will automatically be configured as Bermuda trackers as well.
- 🐛 Fixed error if no devices are saved for setup (ie, CONF_DEVICES is empty) as may happen if one uses *only* Private BLE Devices.
- Added refresh calls to device registry listener
- Improved some mac_format calls by forcing .lower(), since some "addresses" like private ble will not match a MAC-based pattern.
- Fixed new_device signal dispatcher to use full list of devices and check for create_sensor rather than scanning CONF_DEVICES
- Added Private BLE Devices to the iBeacon code, so both are treated as "meta-devices" in that they have data that is provided via the MAC address, but is not …

feat: iOS / iPhone / Private BLE Device / IRK Support!

---

.vscode/launch.json
custom_components/bermuda/__init__.py

Fixes IRK (Private BLE Device) devices not updating their source_address, causing the readings to go stale.

fix: Update IRK device source addresses on change

---

custom_components/bermuda/device_tracker.py

- Default entity name caused confusion by being identical to the Private BLE Device-provided entity name. Appened "Bermuda Tracker" to name to create easily-distinguishable tracker name and id. Fixes issue #144

fix: Create unique Private BLE tracker entity name #144

---

custom_components/bermuda/__init__.py

- private_ble_device now appends translation_key to its device_tracker entity unique_id. Handle either case
- Update device removal handler to properly parse unique_ids for ibeacons and irk, not just mac addresses, but also to gracefully accept deletions if it can't find (stale) devices being deleted.
- linting fix for new black version

fix: Handle new Private_BLE changes in 2024.4

---

custom_components/bermuda/__init__.py
custom_components/bermuda/const.py

Keeping "every address ever seen" causes the processing loop to slow down over time. For example, In my low-density urban environment 5 days gathered 6k entries, all bar 30 were resolvable private addresses (about 10 physical devices, 96 addresses each per day). At 6k entries and only a single proxy, loop time for updates went from 5ms to over 100ms. Dump file size goes from 62kB to 14MB. Trimming IRK source addresses in particular is clearly required, but keeping a cap on other advertisements is wise, too.
Also implemented a cap on total device count, currently 1000. Again, this is only in addition to the number of configured devices, so *should* be OK for almost any use-case, and protects against being flooded with MACs.
- Define `address_type` (replaces `mac_is_random`) to track which …

fix (performance): Pruning of device states

---

custom_components/bermuda/__init__.py

In the calculate_data function within the init.py, two additional checks have been incorporated into the processing loop. The first check skips the iteration if the hist_stamp[i] is None, avoiding errors when accessing uninitialized data. The second check ensures the iteration is skipped if the time difference delta_t is zero or negative, which helps prevent division by zero errors when calculating velocity. These improvements enhance the reliability of the data calculation function by preventing potential crashes and errors during execution.

Add null and non-positive time checks in calculate_data

---

custom_components/bermuda/__init__.py

- Only showed up once on 2024.5.x, submitting new config caused infinite loop due to the listener not being un-subscribed when entry was unloaded.
- Hopefully resolves #185

fix: Resolve infinite loop on config reload in 2024.5

---

custom_components/bermuda/config_flow.py

- In preparation for doing more scanner/device-level settings like ref_power etc.

feat: Split configuration into sub-menus

---

custom_components/bermuda/__init__.py
custom_components/bermuda/coordinator.py
custom_components/bermuda/device_tracker.py
custom_components/bermuda/sensor.py

- Fix race condition in reload that caused wedge/race in 2024.6.0b6 when a new device was added
- Quieted some debug messages re entity creation

Fix!: race condition in 2024.6.0b6

---

custom_components/bermuda/coordinator.py
custom_components/bermuda/diagnostics.py
custom_components/bermuda/services.yaml
custom_components/bermuda/translations/en.json

- `dump_devices` service call now supports:
- `configured_devices` toggle to include explicitly configured devices
- `redact` toggle to anonymise all addresses by adding still-tracable identifiers.
- New Download Diagnostics support for troubleshooting. Uses the new redacted output from `dump_devices`.

feat: Diagnonstics and Redaction support

---

custom_components/bermuda/config_flow.py
custom_components/bermuda/coordinator.py
custom_components/bermuda/diagnostics.py
custom_components/bermuda/translations/en.json

- The configure dialog (options flow) now displays the count of total and recently-active scanners and devices.
- These counts are also include in the diagnostics download.

feat: Show active device and scanner count in configure

---

.github/workflows/release.yaml
hacs.json

- Fixed quoting issue with auto version updates
- Configure HACS to use zipped release files
- Bumped minimum HA version to 2024.6

chore: fix versioning in release zip and HACS settings

---

requirements.txt

- hacs.json already had minver of 2024.6 for HA.
- Update requirements.txt to match.

Bump requirements homeassistant to 2024.6

---

.pre-commit-config.yaml
custom_components/bermuda/__init__.py
custom_components/bermuda/bermuda_device.py
custom_components/bermuda/bermuda_device_scanner.py
custom_components/bermuda/binary_sensor.py
custom_components/bermuda/config_flow.py
custom_components/bermuda/const.py
custom_components/bermuda/coordinator.py
custom_components/bermuda/device_tracker.py
custom_components/bermuda/diagnostics.py
custom_components/bermuda/entity.py
custom_components/bermuda/log_spam_less.py
custom_components/bermuda/sensor.py
custom_components/bermuda/switch.py
custom_components/bermuda/util.py
pyproject.toml
requirements.txt
tests/conftest.py
tests/test_config_flow.py
tests/test_init.py

Switches to use the ruff linter with configs based off of:
https://github.com/home-assistant/core/blob/dev/pyproject.toml
and
https://github.com/ludeeus/integration_blueprint
Disable a lot of things that wouldn't auto fix just to limit how many changes i was making.
This makes it match a bit more with what HA code looks like so that in the future migrating to Core wouldn't be as much of a challenge.
All changes but ~5 are automatic, disabled anything that would require significant changes.

Change to HA config of ruff

---

custom_components/bermuda/__init__.py
custom_components/bermuda/config_flow.py
tests/conftest.py
tests/test_config_flow.py
tests/test_init.py
tests/test_switch.py

Changes:
- Removed async_setup - when configuration setup isn't done in yaml, it doesn't need to exist.
- Changed to OptionsFlowwithConfigEntry
- Created two fixtures to get either a mockconfigentry or a mock config entry that has been set up
- Changed how setup of entries works
- Instead of directly calling functions in init, we now use hass to call them
I will have to change either this Pr or the other depending on which gets merged first

Fix tests and change some objects

---

custom_components/bermuda/bermuda_device.py
custom_components/bermuda/bermuda_device_scanner.py
custom_components/bermuda/config_flow.py
custom_components/bermuda/const.py
custom_components/bermuda/coordinator.py
custom_components/bermuda/translations/en.json
pyproject.toml

Per our discussions - here's part 1 and 2 of our discussion. It still needs a bit more work - so I wouldn't merge it yet, but it is ready for some review
Related to:#45
Todo:

Add Calibration at a per-scanner level

---

custom_components/bermuda/__init__.py
custom_components/bermuda/bermuda_device_scanner.py
custom_components/bermuda/config_flow.py
custom_components/bermuda/const.py
custom_components/bermuda/coordinator.py
custom_components/bermuda/translations/en.json

- Add table and nicer formatting to initial config dialog status info.
- Add tables and instructions to calibration steps to make choosing values easier
- Error checking and mac case-folding in _get_bermuda_device_from_registry
- pluralise CONF_RSSI_OFFSET
- add typing to coordinator.scanner_list
- add coordinator.get_active_scanner_summary
- add (copious) instructions to calibration1
- pluralise step name calibration2_scanners

feat: Config status and Calibration additions

---

custom_components/bermuda/bermuda_device.py
custom_components/bermuda/bermuda_device_scanner.py
custom_components/bermuda/config_flow.py
custom_components/bermuda/const.py
custom_components/bermuda/coordinator.py
custom_components/bermuda/diagnostics.py
custom_components/bermuda/entity.py
custom_components/bermuda/translations/en.json

- Tidy of diagnostic tables in options_flow
- Add model to device entries to help identify un-named devices
- Label and text tweaks
- Switch to a linear options_flow, looping back to menu caused processing to break.
- Handle where selected device has not been see by selected scanner
- Translate scanner names back to addresses for saving in options
- Flattened ObjectSelector yaml block for scanner offsets
- Cleaned some BermudaDeviceScanner stuff

Further Calibration improvements

---

custom_components/bermuda/entity.py
custom_components/bermuda/sensor.py

Finally got around to having some time to do this

Add a global device to keep track of some helpful data.

---

custom_components/bermuda/__init__.py
custom_components/bermuda/config_flow.py
custom_components/bermuda/coordinator.py
custom_components/bermuda/device_tracker.py
custom_components/bermuda/diagnostics.py
custom_components/bermuda/entity.py
custom_components/bermuda/sensor.py
tests/conftest.py
tests/test_init.py

- Change to use runtime_data instead of hass.data
- Limit the amount of times that we update the config flow.

Convert to runtime_data

---

custom_components/bermuda/bermuda_device.py
custom_components/bermuda/coordinator.py

Clean up handler for device registry changes
- Hopefully fixes Device slow / crashes when renaming a device #341 
- Avoids multiple sequential calls to updates on scanners and private ble devices, instead filters DR event to work out type of change. Hopefully reduces the changes of getting into race conditions from multiple async updates.
- Switch to async_refresh on state change, as first_refresh likely to cause issues.
- Moved to single device_registry, entity registry in coordinator.
- Fix crash in 2024.11 when async_config_entry_first_refresh called while entry not fully loaded.

Stability and performance clean-ups

---

custom_components/bermuda/coordinator.py
custom_components/bermuda/manufacturer_identification/member_uuids.yaml

What spawned my conversation with you was that I got a tile for tracking my dog, and I struggled to find it a bit with Bermuda since it didn't have a name attached. I think adding manufacturer name to the end of a prefname when we don't have a real name and we are just making one up is a good step to help users figure out where the device they want to add is.

Add manufacturer to prefname.

---

custom_components/bermuda/bermuda_device_scanner.py
custom_components/bermuda/const.py
custom_components/bermuda/coordinator.py

- Refactor _refresh_scanners to be more efficient, and to handle the case where a scanner still exists but is no longer a scanner.
- Refactor coordinator.init() to move callbacks out into class methods.
- Tamed down lots of debug logging
- Altered self.last_config_entry_update to use MONOTONIC_TIME(), and changed cooldown to a const of 10 seconds, and included check for parallel save tasks.
- Removed assert that excluded scanners from area-by-mindist

fix: Handling retired or changed scanners

---

custom_components/bermuda/bermuda_device.py
custom_components/bermuda/bermuda_device_scanner.py
custom_components/bermuda/coordinator.py

- bug introduced from per-device ref_power changes.
- There is another bug in that metadevices will fight other devices about who's ref_power to use. Will address separately.
- Fixes #371

fix: Metadevices not going `Unavailable`

---

custom_components/bermuda/coordinator.py

- Fixes Reduce logging - remove save config at info level #364
- Fixes How to remove entities for proxies that no longer exist #214
- Stops Bermuda doing multiple save-outs to config_entry.data for scanner configs.
- Fixes a lot of reload-churn during initial startup, Bermuda now only loads once if the scanner setup hasn't changed.
- Likely fixes some race-condition-based performance / lockup issues that might have happened very occasionally.
- Only save the necessary fields out for scanner info, to avoid ephemeral data causing extra reloads.
- This plus the change to scanner identification in previous release resolves being unable to remove entities on devices that relate to non-present scanners (or scanners that are no longer scanners).
- Bonus fix, include IRK devices in action …

fix: Scanner config multiple saves.

---

custom_components/bermuda/bermuda_device_scanner.py

- Fixes Devices go unavailable every few mins for a few seconds #362
- Fix insert when velo_max is exceeded but the hist_distance_by_interval was empty (such as after MAC rotation)

fix: IRK devices temporary unavail on mac rotation fixes #362

---

custom_components/bermuda/config_flow.py
custom_components/bermuda/translations/el.json
custom_components/bermuda/translations/en.json
custom_components/bermuda/translations/nl.json

Removed device_count and scanner_count strings. The variables from these strings have been split into separate keys: device_counter_active, device_counter_devices, scanner_counter_active, scanner_counter_scanners. These keys only contain the numerical values ​​and are applied as such in the translation file.
_(I also tried to move the status messages  to the translation file, but I haven't succeeded yet. The preparations for this are already in the .json translation files.)_
For this reason, the translation files for Greek and English have also been updated to work with this adjustment. In addition, I have created a translation file for the Dutch language.
I tested these changes with Home Assistant 2024.11.3

Add Dutch translation and reduce hardcoded language in scripts

---

custom_components/bermuda/config_flow.py

- Cleaned up calibration table display
- Linting and ruff fixes

feat: Better-looking per-scanner calibration table

---

custom_components/bermuda/config_flow.py

When no device is selected while submitting calibration1, would cause the config flow to error out due to an invalid flow step name.

fix: config flow failure when no device in calibration step 1

---

custom_components/bermuda/coordinator.py

Last changes caused issue with hci0 or other local adaptors showing up with None for device name.

fix: bug when choosing local bt adaptor name

---

custom_components/bermuda/bermuda_device.py
custom_components/bermuda/bermuda_device_scanner.py
custom_components/bermuda/const.py
custom_components/bermuda/coordinator.py
custom_components/bermuda/translations/en.json

If scanners are found that don't have an area assigned to them,
a repair issue is raised to advise the user to do so.

feat: raise repair for scanners without areas

---

custom_components/bermuda/bermuda_device.py
custom_components/bermuda/sensor.py

Fixes #202 
This change adds a new Area Last Seen sensor that contains the last area seen. It is the same as 'Area' but is not reset to 'None'.
This change also exposes the existing last_seen property as a Last Seen timestamp sensor. 
These sensors are disabled by default by the existing logic in the base classes.
Please let me know if there is a different way you imagined this to be implemented or if this is the wrong time stamp or whatever.

Add 'Area Last Seen' and 'Last Seen' sensors

---

custom_components/bermuda/coordinator.py

When a scanner does not have a valid area set
and the device is closest to that scanner, set
the area sensor to `Invalid Area for [scanner.name]`, which will hopefully encourage looking at the repair issue!

feat: Flag Area sensor if scanner area is invalid

---

custom_components/bermuda/bermuda_device.py
custom_components/bermuda/bermuda_device_scanner.py
custom_components/bermuda/config_flow.py
custom_components/bermuda/coordinator.py
custom_components/bermuda/device_tracker.py
custom_components/bermuda/entity.py

- These changes might break integrations that are relying on the names of devices or entities, or on the naming structure of the bermuda.dump_devices output. Those relying on unique_id etc should not be affected.
- Fixed some issues where devices names did not have good defaults.
- change bermuda_device to store object of closest scanner, rather than just its name.
- tidy/clarify area selection logic.
- remove scanner list from _refresh_scanners params
- remove log warning about newly init metadevices fixes #405

refactor!: fixed naming of devices for consistency

---

custom_components/bermuda/bermuda_device.py
custom_components/bermuda/config_flow.py
custom_components/bermuda/const.py
custom_components/bermuda/coordinator.py
custom_components/bermuda/sensor.py

The "Area Last Seen" sensor (if enabled) now restores state after a HA restart. Note that the state is only saved periodically by HA and on graceful shutdown, so a power outage etc might not reflect the most recent state on restart.
Also included:
- fix for the Area sensor sometimes remaining locked
to area instead of returning to unknown, likely
due to simplifications made in recent commits.
- feat: only calculate nearest-area for tracked devices
- refactor: renamed beacon_type to metadevice_type
- chore: comment cleaning, linting

feat: Restore Area Last Seen on HA restart, fix Area not timing out

---

custom_components/bermuda/coordinator.py

- devreg and entity state listeners were not wrapped in async_on_unloads, so they still triggered on their stale objects after the entry had been reloaded.

fix: stale listeners causing oddities.

---

.pre-commit-config.yaml
custom_components/bermuda/bermuda_device.py
custom_components/bermuda/coordinator.py
pyproject.toml

- This hopefully fixes #375
- New iOS (18.3+ I think) sends a flurry of BLE broadcasts at different times (mostly screen [un]lock) using *different* MAC addresses. Their order appears not very deterministic, so previous addresses will often appear on future updates.
- Bermuda now registers a callback with PBD integration so we get realtime updates on new MACs, so we don't miss any between update runs. As we store the recent MACs this resolves the issue.
- First clue was Android15 doing a similar thing, but its address- cycling was slower.
- Linting, tidying. Also chilled pylint on line-length.

fix: iOS flipping to unknown indeterminately

---

custom_components/bermuda/bermuda_device.py
custom_components/bermuda/sensor.py

- If an area has an icon defined, Bermuda will use that icon for the Area, Distance, and Last Seen Area
entities.

feat: Area and distance entities use area icon

---

custom_components/bermuda/__init__.py
custom_components/bermuda/bermuda_device.py
custom_components/bermuda/bermuda_device_scanner.py
custom_components/bermuda/config_flow.py
custom_components/bermuda/const.py
custom_components/bermuda/coordinator.py
custom_components/bermuda/device_tracker.py
custom_components/bermuda/entity.py
custom_components/bermuda/log_spam_less.py
custom_components/bermuda/manufacturer_identification/company_identifiers.yaml
custom_components/bermuda/number.py
custom_components/bermuda/sensor.py
custom_components/bermuda/util.py

- more efficient processing of updates
- better handling of proxies being added/removed
- improvements to naming when first adding / browsing in select devices
- feat: Shorten/redact scanner macs in configure status display
- distance_to... sensors are now created/removed in realtime as scanners come and go.
- fix: startup is now faster due to better asyncio usage
- bermuda.dump_devices service/action format has changed! If you are using this please test as many items have been restructured
- scanners dict renamed to "adverts", now keyed as device/scanner tuples
- clarification on processing order for metadevices
- no longer save/restore scanner list in config, now dynamically CRUD'd
- implement scanner list as properties to centralise changes
- add customisations to manufacturer lookups …

feat: significant restructuring

---

custom_components/bermuda/bermuda_advert.py
custom_components/bermuda/bermuda_device.py
custom_components/bermuda/coordinator.py

More accurately represents the class, which is the advertisement that ties a device and scanner together.

chore: ren BermudaDeviceScanner to BermudaAdvert

---

custom_components/bermuda/bermuda_device.py
custom_components/bermuda/bermuda_irk.py
custom_components/bermuda/const.py
custom_components/bermuda/coordinator.py
custom_components/bermuda/diagnostics.py

- new BermudaIrk class handles all IRK data from PBLE and also tracks irks independently.
- full history tracking for past macs both matched and unmatched

fix: new irk_manager to cover all traffic types

---

custom_components/bermuda/bermuda_device.py
custom_components/bermuda/bermuda_irk.py
custom_components/bermuda/coordinator.py
custom_components/bermuda/diagnostics.py
custom_components/bermuda/util.py

The irk_manager introduced in v0.8.2beta3 did not redact the irk and MAC addresses collected for diagnostics. This is now fixed.
- improved performance of redact_data by moving mac format expansions into redaction_list_update and correcting logic
- quieted debug logger on metaNoAdsFor / "Metadevice .. no adverts for source MAC .. found during update_metadevices"
- quieted "scanner stamps for .. should not go backwards" to debug fixes #580

fix: redactions in irk_manager diagnostics

---

custom_components/bermuda/bermuda_advert.py
custom_components/bermuda/coordinator.py

- fixes #579 where runtime error caused devices to go `unavailable` for about a second each time.
- Also restores bluecharm functionality for uuid change on movement.

fix: bluecharm uuid regression and runtime error

---

custom_components/bermuda/__init__.py
custom_components/bermuda/const.py
custom_components/bermuda/coordinator.py
custom_components/bermuda/util.py

- Fixed a very silly bug in mac_explode_formats that exploded too much (to individual chars!)
- Redaction purge was using a separate task for clearing redaction_data which added compexity. Changed to use device pruning instead to bring it into the regular loop and reduced expiry time to 10 mins instead of hours.

fix: mac_explode, move redaction purge to pruning

---

custom_components/bermuda/bermuda_device.py
custom_components/bermuda/coordinator.py

- Fixed devices being `unavailable` at startup if the device is away at boot. Now away devices will start at `unknown`/`away` on bootup if they are note present.
- Fixes #581

fix: Devs start `unavailable` instead of `unknown

---

custom_components/bermuda/bermuda_device.py
custom_components/bermuda/coordinator.py

- move most of _rebuild_scanner_list from coordinator to bermuda_device.async_as_scanner_resolve_device_entries
- rename _device_registry and _entity_registry to dr, er
- remove dead code and comments related to scanner saveout

refactor: move scanner init into bermuda_device

---

custom_components/bermuda/bermuda_device.py
custom_components/bermuda/const.py
custom_components/bermuda/coordinator.py
custom_components/bermuda/device_tracker.py
custom_components/bermuda/entity.py
custom_components/bermuda/sensor.py

- basic floor support. Uses area_id to directly map to current floor.
- Floor sensors are automatically enabled at startup if any area is
assigned to any floor.
- attributes on the floor entity give access to floor_id and floor_level
- icons for Floor sensors also take the floor icon if set.
Signed-off-by: Ashley Gittins <ash@ajg.net.au>

feat: initial floors support

---

custom_components/bermuda/bermuda_irk.py
custom_components/bermuda/device_tracker.py

- Fixes #637. Params for bleak.BLEDevice.__init__() changed (twice).
- Also fixes ConfigEntryNotReady in forwarded platform device_tracker

Fix 2025.8 issue with BLEDevice.__init__() #637

---

custom_components/bermuda/bermuda_advert.py
custom_components/bermuda/bermuda_irk.py

- Various stamp-checking log lines have been reduced from warning or info to debug.
- Includes "lacks stamp, unexpected", noted in #584
- disabled typecheck on BLEDevice call, for linting.

Lower logging level for unexpected stamps
