.github/ISSUE_TEMPLATE/issue.md

- change issue template to request configuration screenshot instead of yaml. Note re MACs and privacy.

chore: Update issue template for config screenshot

---

README.md
TODO.md
custom_components/bermuda/__init__.py
custom_components/bermuda/config_flow.py
custom_components/bermuda/const.py
custom_components/bermuda/sensor.py

- initial check-in of basic iBeacon support.
- iBeacon works OK, but does spew errors re duplicate IDs when reloading or configuring. Will address these separately since they don't stop it from working, and are issues outside of iBeacon itself.
- Added check after sensor creation to avoid sending PDUC creation if config is not yet loaded.

feat: iBeacon Support!

---

custom_components/bermuda/__init__.py

- Reduced update_interval to 0.9seconds (vs 5) for faster updates
- cleaned up some dead code, commenting.

Faster Polling (0.9seconds instead of 5), cleanups

---

custom_components/bermuda/__init__.py

- Was using state machine for finding entries, but was assuming naming pattern of entity_id invalidly.

fix: properly search for Private ble devices via config entries

---

.devcontainer.json
.vscode/settings.json
custom_components/bermuda/config_flow.py

- fix: FlowResult import, form placeholders  
- fixed some config_flow.py import and placeholders after testing against HA 2024.4.0b4
- Devcontainer updates python 3.12

Config_flow fixes, devcontainer updates

---

custom_components/bermuda/__init__.py
custom_components/bermuda/const.py

- chore: Remove deprecated async_add_job
- linting: initial round of type checking tightening.

Chore: Remove deprecated async_add_job, linting

---

custom_components/bermuda/__init__.py
custom_components/bermuda/const.py

fix: Ensure scanner area updates are persisted to config data

---

custom_components/bermuda/__init__.py

Summary of changes:
- In the update_advertisement function, the timestamp comparison check has been enhanced. An additional check for a non-None value before comparing with the current timestamp has been added, which prevents potential errors when handling undefined values.
- In the _async_update_data function, the MAC address check has been improved. A check for a non-empty string has been added before verifying whether the first character of the address is one of 4, 5, 6, 7. This change increases the reliability of address identification and prevents possible errors in parsing unformatted data.

fix(bermuda): Improved condition checks and handling of MAC addresses

---

custom_components/bermuda/coordinator.py

- removed some calls that were not strictly necessary and might cause thread/async issues.
- changed _refresh_scanners and how it tracks full init.
- some cleanups

fix: removed some calls that might not be thread-safe

---

custom_components/bermuda/config_flow.py

- Previously the "Configured Devices" drop-down gathered its list from the backend's current list of bluetooth adverts. We now generate this list from Bermuda's internal state of all devices. This lets us show devices that may have been pruned from the backend (due to age) and to leverage Bermuda's knowledge about devices, if they are random MACs etc.

feat: Config flow device list improvements

---

custom_components/bermuda/coordinator.py

- If there were no "present" configured_devices at startup, Bermuda's coordinator would not receive any future updates. Added stamp and check in handle_advert to trigger update if one has not been run in 2*update_interval. Fixes #235 Entities not leaving Unavailable state until after integration reload

fix: Entities not updating if away at startup

---

custom_components/bermuda/bermuda_device.py
custom_components/bermuda/coordinator.py

- Previously absent devices would appear as "unavailable" on all entities. Now sensors will show "unknown" and device_tracker will show "Away" if the device is not present at start-up.
- Moved address-type logic into bermuda_device.py
- On first update create all device entries so sensors are defined regardless of visibility of advertisements.
- Fixes #228

fix: Absent devices now show as "Away" on startup

---

.github/release-drafter.yml
.github/workflows/release-drafter.yml
.github/workflows/tests.yaml
hacs.json

- Reverted HACS back to zip releases as unable to find solution to versioning, will go to branch-based pre-releases.
- Renamed workflow job pre-commit to linting.
- Release-drafter config changes

Workflow and HACS changes

---

custom_components/bermuda/coordinator.py
custom_components/bermuda/entity.py

- fixes Failed to find Scanner (local USB Bluetooth) #386
- linting

fix: Local USB Bluetooth detection

---

README.md

Remove manual HACS install steps

---

custom_components/bermuda/coordinator.py

Some beacons send 22-byte adverts that lack the tx_power byte. Added checks to avoid IndexErrors processing those packets, but still allow using the device for tracking.

fix: handle malformed iBeacon packets fixes #466

---

custom_components/bermuda/coordinator.py

- Pixel Android recently started getting a lot of Unknown periods, which were caused by the phone sending a few packets with a new random MAC (for other purposes) then reverting to the previous IRK-MAC to continue sending packets.
Bermuda now checks old addresses of metadevices in order to ensure adverts are counted from any currently valid IRK address.

fix: IRK devices going Unknown

---

.github/workflows/tests.yaml
custom_components/bermuda/__init__.py
custom_components/bermuda/const.py
custom_components/bermuda/coordinator.py
custom_components/bermuda/manifest.json
requirements.txt

Signed-off-by: Ashley Gittins <ash@ajg.net.au>

fix: async usage addressing #456

---

custom_components/bermuda/coordinator.py

- Restored update trigger to async_handle_advert because some folk disable all their entities
- add more logging to diagnostics to get to the root of long exports.

fix: restore on_advert trigger and add diags log

---

custom_components/bermuda/bermuda_irk.py

- previous non-matched IRK addresses were not being saved to cache, so retarting Bermuda left IRK devices as `unknown` until a new MAC was rotated. This fixes that so IRK devices work immediately on reload, even if PBLE integration is not current.

fix: irk checks on cached addresses
